language: python
sudo: false
branches:
  only:
    - packageRestructure
python:
  - "2.7"

install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt

script: 
  - py.test analyzeMOPS --cov=analyzeMOPS

after_success:
  - coveralls