!!python/object:MopsParameters.MopsParameters {_angTol: '5', _bufferSize: '1000',
  _decAccelMax: '0.02', _decTol: '0.002', _detErrThresh: '0.0004', _detectMin: '6',
  _earliestLastEnd: null, _keepOnlyLongest: 'False', _latestFirstEnd: null, _leafNodeSizeMax: null,
  _method: greedy, _nightMin: '3', _raAccelMax: '0.02', _raTol: '0.002', _rmSubsets: 'False',
  _rmsMax: '0.001', _useRMSfilt: 'True', _vMax: '0.5', _vMin: '0.0', _vTol: '0.05',
  _windowSize: '15'}
